Mobile skeleton
elmar8287/mobil-version-portfolio pull request #1
Opened 2021-06-04 14:29 UTC by elmar8287

This project consists following:

- Here created two sections, "Works" and "About myself".
- Here I used CSS Flexbox and Grid to build the layout.

2021-06-04 15:08 UTC, Temmarie reviewed
## Status: Invalid ❗ 

### Hi @elmar8287  👋🏾 , 

 **While you made a great effort in this project, unfortunately, I cannot proceed to review your code.**

### Invalid Code Review Request

I have to mark this submission as invalid because you have submitted the PR (`Portfolio: mobile version`)  under the wrong project(`Portfolio: setup and mobile version skeleton`). Kindly use the right link and submit it for review.


#### Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

#### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-06-04 15:10 UTC, Dipeshtwis commented
### Reviewing this PR for (Portfolio: mobile version)

2021-06-04 15:41 UTC, Dipeshtwis requested changes
Hi @elmar8287, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: Good use of grid and Flexbox property.
:+1: your codebase is looking awesome. :muscle: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

**_Check the comments under the review._**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**_Check the comments under the review._**

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-04 15:41 UTC, Dipeshtwis commented on hintrc
> +    "meta-viewport"
- You have updated the `.hintrc` file which is not recommended. You have removed `"no-inline-styles:error"`check which is not good. It will make sure to not use inline styling and make you a better programmer. Please use this [file ](https://github.com/microverseinc/linters-config/blob/master/html-css/.hintrc) and not update or remove anything.

2021-06-04 15:41 UTC, Dipeshtwis commented on index.html
> +          ><img src="images/logo.svg" alt="Home" width="76" height="20"
- [ ] Do not use inline styling in HTML file.

2021-06-04 15:41 UTC, Dipeshtwis commented on index.html
> +    <div class="works grid-container">
- [ ] The container of the section supposed to be a `section` tag.

2021-06-04 15:41 UTC, Dipeshtwis commented on README.md
> +This is the first milestone in the process of creating our portfolio website.
[Optional]
- I recommend to update the project description of the current milestone.
- You can add how to run the project (first clone it with the command `git clone https://yourrepo.git/` and then run (or double click on the index.html file).

2021-06-04 15:41 UTC, Dipeshtwis commented on index.html
> +            ><img src="images/icons/menu.svg" alt="Menu" width="24" height="24"
- [ ] Here too, You can make a class and use `height` and `width` property in CSS.

2021-06-05 09:53 UTC, henatan99 commented on hintrc
> +    "meta-viewport"
- [ ] @Dipeshtwis, I think .hintrc is for local checks. As long as the student didn't touch the linters.yml file in the GitHub/workflows, I think this comment can be OPTIONAL.

2021-06-05 09:55 UTC, henatan99 commented on index.html
> +    <div class="works grid-container">
- [ ] This issue is not addressed!

2021-06-05 09:57 UTC, henatan99 commented on index.html
> +            ><img src="images/icons/menu.svg" alt="Menu" width="24" height="24"
This issue is addressed! Nice work! :clap:

2021-06-05 09:59 UTC, henatan99 commented on index.html
> +          ><img src="images/logo.svg" alt="Home" width="76" height="20"
- [ ] This issue is not addressed. While it does not mean that you cannot use inline stylings at all, the best practice way as pointed out by the previous reviewer is to use staying in CSS. I will leave this comment as optional.

2021-06-05 10:05 UTC, henatan99 requested changes
Hi Elmar, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-05 10:10 UTC, henatan99 requested changes
Hi Elmar, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-05 10:10 UTC, henatan99 commented on index.html
> +    <div class="works grid-container">
- [ ] This issue is not addressed! For semantic's sake, make sure to have the requested change by the previous reviewer before you submit for another review.

2021-06-05 10:10 UTC, henatan99 commented on index.html
> +          ><img src="images/logo.svg" alt="Home" width="76" height="20"
- [ ] OPTIONAL: While it does not mean that you cannot use inline stylings at all, the best practice way as pointed out by the previous reviewer is to use staying in CSS.

2021-06-05 12:28 UTC, elmar8287 commented
Dear @henatan99,

I have fixed your comment regarding "The container of the section supposed to be a section tag"

Please, could you submit PR.

My best regards,

Elmar

2021-06-05 16:32 UTC, elmar8287 commented on index.html
> +    <div class="works grid-container">
I did fixing of your changes. Please have a look and give your confirmation

2021-06-05 17:10 UTC, merged

2021-06-05 20:03 UTC, smcommits reviewed
### Status: Approved 👍🏽 

Hi @elmar8287, 

## You have done a great job! Your project is complete. This PR is now approved. Also, I can see that you have already merged the PR. You should do it after the project has been approved. But, don't worry too much about it. Just letting you know so that you don't make the same mistake again.  

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.